#!/bin/sh

##
## Send a log message to Hakka logs
##

if [ $# = 0 ]; then
    message=`cat`
else
    message="$@"
fi

data='{"log":"'"$message"'"}'

curl -d "$data" "https://www.hakkalabs.co/api/webhooks?service=custom&token=$(secret hakka)"
