#! /bin/sh

## -*- mode: sh; -*-

die()
{
    echo $1 >&2

    exit 1
}

all_modules()
{
    find modules -type f -name 'build.gradle' | sed 's|/build.gradle||'
}

gen_module_entries()
{
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '  <project version="4">'
    echo '    <component name="ProjectModuleManager">'
    echo '      <modules>'

    while read LN; do
        MOD_CAT0=$(echo $LN | cut -d/ -f2)
        MOD_CAT1=$(echo $LN | cut -d/ -f3)
        MOD_NAME=$(echo $LN | cut -d/ -f4)

        if [ -z "$MOD_NAME" ]; then
            MOD_CAT="$MOD_CAT0"
            MOD_NAME="$MOD_CAT1"
        else
            MOD_CAT="$MOD_CAT0/$MOD_CAT1"
        fi


        FILE_PATH='$PROJECT_DIR$/portal/'$LN"/$MOD_NAME.iml"

        echo '        <module fileurl="file://'$FILE_PATH'" filepath="'$FILE_PATH'" group="'$MOD_CAT'" />'
    done

    echo '    </modules>'
    echo '  </component>'
    echo '</project>'
}

[ -d modules ] || die "This script should be executed in the project root directory."

all_modules | gen_module_entries
