#! /bin/sh

if which osascript > /dev/null; then
    wrapper=$(which reattach-to-user-namespace)
    $wrapper osascript -e "display notification \"$2\" with title \"$1\""
elif which notify-send > /dev/null; then
    notify-send "$1" "$2"
else
    exit 1
fi
