#! /usr/bin/awk -f

/^[a-zA-Z-]+:[ \t]*$/ || /[^,]+,$/ {
    print "[!] line " NR ": Missing newline escape:", $0
}

/@.*\/lib\/portal\// {
    print "[!] line " NR ": Explicit reference to lib path; use @${app.server.lib.portal.dir}:", $0
}
