#!/bin/sh

manifest="META-INF/MANIFEST.MF"
property="Import-Package"

while getopts m:p: opt; do
    case $opt in
        m) manifest=$OPTARG ;;
        p) property=$OPTARG ;;
        ?) echo "unknown option -$opt" ;;
    esac
done

while [ $OPTIND -gt 1 ]; do
    OPTIND=$(($OPTIND - 1))
    shift
done

[ $# -lt 1 ] && echo "usage: $(basename $0) [-p <property-name>] [-m <manifest-file>] jar-file ..." && exit 64 # EX_USAGE

package_property()
{
    awk -v PROPERTY=$1 '
BEGIN { prop_rx = "^" PROPERTY ":" }

prop_rx {
    prop_decl = 1

    sub(prop_rx "[ \t]+", "")
}

/^[a-zA-Z_-]+:/ {
    prop_decl = 0
}

prop_decl {
    sub(/^[ \t]+/, "")

    print
}
'
}

for f in "$@"; do
    unzip -p $f $manifest | package_property $property | tr -d '\r\n' | tr ',' '\n' | sort -u
done
