#! /bin/sh

die()
{
    if [ -n "$1" ]; then
	echo $1
    fi

    exit 128
}

pull()
{
    git pull --rebase "upstream" $1
}

push()
{
    git push "origin" $1
}

git status > /dev/null || die

git_branch=$(git status -sb | sed 's/[^.]*\.\.\.//')

(pull $git_branch && push $git_branch) || die

if (pwd | grep portal); then
    cd $(groot) && ant all setup-jrebel
else
    echo "skipping ant all, not in portal"
fi
