#! /bin/sh

##
## scan-lang, get all language keys used in .java and .jsp files.
##
## To get a list of all language keys, cd to your OSGi module root
## directory and execute this script with no arguments.
##

src=$(groot)/portal-impl/src/content

grep -E -o -h '"[a-z]+(-|\.)[a-z\.-]+"' $(find . -name '*.java' -or -name '*.jsp') \
    | tr -d '"' \
    | sort -u \
    | while read pn; do \
          (grep "^$pn=" $src/Language.properties > /dev/null && echo $pn); \
      done
