#! /bin/sh

if [ $# = 0 ]; then
    echo "usage: $(basename $0) [-c] <regexp> ..."
    exit 64 # EX_USAGE
fi

only_copy=0

if [ "$1" = '-c' ]; then
    shift
    only_copy=1
fi

src=$(groot)/portal-impl/src/content

rem_exprs()
{
    echo '/^'"$@"'=/' | sed -e 's/$/d/' -e 's/ /=\/d -e \/^/g'
}

keep_exprs()
{
    echo '/^'"$@"'=/' | sed -e 's/$/!d/' -e 's/ /=\/!d -e \/^/g'
}

for fn in $src/Language*.properties; do
    sed -e $(keep_exprs "$@") $fn >> $(basename $fn)
    [ "$only_copy" -eq 0 ] && sed -i '' -e $(rem_exprs "$@") $fn
done
