#!/bin/sh

usage()
{
    echo "usage: $(basename $0) [-m manifest-file] jar-file ..."
}

manifest=META-INF/MANIFEST.MF

while getopts m: opt; do
    case $opt in
      m) manifest=$OPTARG ;;
      ?) usage && exit 64 ;;
    esac
done

while [ $OPTIND -gt 1 ]; do
    OPTIND=$(($OPTIND - 1))
    shift
done

[ $# -eq 0 ] && usage && exit 64

for j in "$@"; do
    [ -f $j ] || ( echo "file $j not found." && exit 66 )
done

for j in "$@"; do
    unzip -p $j $manifest | \
      awk '/^[a-zA-Z-]+:/ { print substr($0, 0, index($0, ":") - 1) }' | \
      sort
done
