#! /bin/sh

config_dir=$HOME/.scripts.d/ts
mkdir -p $config_dir || exit $?

usage()
{
    echo "usage: $(basename $0) [ -a <test-set> ] <test-class> ..."
    echo "       $(basename $0) -d <test-set>"
    echo "       $(basename $0) -l"
}

cmd=run

while getopts a:d:l opt; do
    case $opt in
	a) cmd=define-set
	   set_name=$OPTARG
	   ;;

	d) cmd=delete-set
	   set_name=$OPTARG
	   ;;

	l) cmd=list ;;
	?) usage && exit 64 ;;
    esac
done

while [ $OPTIND -gt 1 ]; do
    OPTIND=$(($OPTIND - 1))
    shift
done

if [ $cmd = run -a $# -eq 1 -a -f "$config_dir/$1" ]; then
    set_name=$1
elif [ $cmd = run -a $# -gt 0 ]; then
    cmd=define-set
fi

if [ -z "$set_name" ]; then
    branch_name=$(git symbolic-ref -q HEAD | cut -d/ -f3)
    branch_name=${branch_name:-$(git rev-parse --short HEAD)}

    set_name=$branch_name
fi

config_file=$config_dir/$set_name

[ ! -f $config_file ] && echo "no configuration file $config_file found." && exit 66

case $cmd in
    run)
	for test_class in $(cat $config_file); do
	    ant test-class -Dtest.class=$test_class || exit $?
	done
	;;

    list)
	ls -1 $config_dir ;;

    delete-set)
	rm $config_file ;;

    define-set)
	rm $config_file
	
	for regexp in $*; do
	    /bin/echo $regexp >> $config_file
	done
	;;
esac
