#! /bin/sh

config_dir=$HOME/.scripts.d/ts
mkdir -p $config_dir || exit $?

usage()
{
    echo "usage: $(basename $0) [ -a <test-set> ] <test-class> ..."
    echo "       $(basename $0) -d <test-set>"
    echo "       $(basename $0) -l"
}

cmd=run

while getopts a:d:l opt; do
    case $opt in
	a) cmd=define-set
	   set_name=$OPTARG
	   ;;

	d) cmd=delete-set
	   set_name=$OPTARG
	   ;;

	l) cmd=list ;;
	?) usage && exit 64 ;;
    esac
done

while [ $OPTIND -gt 1 ]; do
    OPTIND=$(($OPTIND - 1))
    shift
done

if [ $cmd = run -and $# -gt 0 ]; then
    cmd=define-set

    branch_name=$(git symbolic-ref -q HEAD | cut -d/ -f3)
    branch_name=${branch_name:-$(git rev-parse --short HEAD)}

    set_name=$branch_name
fi

config_file=$config_dir/$set_name

if [ $# = 0 ]; then

    ## Execute configured tests

    if [ ! -f $config_file ]; then
	echo "no configuration file $config_file found." && exit 66
    fi

    for test_class in $(cat $config_file); do
	ant test-class -Dtest.class=$test_class || exit $?
    done
elif [ $# = 1 -a $1 = '-l' ]; then
    ls -1 $config_dir
elif [ $# = 2 -a $1 = '-d' ]; then
    test -f $config_dir/$2 && rm $config_dir/$2
else
    ## Configure current branch or alias with given test class names.
    
    test -f $config_file && rm $config_file
	
    for regexp in $*; do
	/bin/echo $regexp >> $config_file
    done
fi
